### ISSUE TITLE
Update documentation and update the "based" statement

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [christiandaley/signals2#29]
I don't know if I'm misunderstanding this, but the readme file says that this library is "based" on boost::signal2... it's not. Based means that it uses C++ to Rust bindings to the job. I think it's better to say that the "idea" is based on boost::signal2. People hate using libraries that have bindings in general, and this library doesn't seem to have that, but gives that impression in its readme file.

**Comment by christiandaley** [comment]
Maybe I should say "inspired by" instead?

**Comment by TheQuantumPhysicist** [comment]
Sounds good. That conveys the correct meaning too.
